<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.0 on darwin)" generated="20201221 22:21:48.038" rpa="false">
<suite id="s1" name="TestCases" source="/Users/swapan.chhabra/PycharmProjects/CasperHealthAssignment/TestCases/tc01_verify_steps_added.robot">
<test id="s1-t1" name="TC01 Verify Steps Added">
<kw name="Launch Application" library="Common_Keywords" type="setup">
<doc>Launching App http://0.0.0.0:4723/wd/hub</doc>
<arguments>
<arg>${remote_url}</arg>
</arguments>
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>${remote_url}</arg>
<arg>platformName=${platformname}</arg>
<arg>deviceName=${devicename}</arg>
<arg>appPackage=${apppackage}</arg>
<arg>appActivity=${appactivity}</arg>
<arg>appwaitactivity=${appwaitactivity}</arg>
<arg>automationName=${automationname}</arg>
<arg>noReset=${no_reset}</arg>
</arguments>
<assign>
<var>${app}</var>
</assign>
<msg timestamp="20201221 22:21:48.363" level="INFO">Could not connect to port 4723 on host 0.0.0.0</msg>
<msg timestamp="20201221 22:21:48.363" level="INFO">Could not get IP address for host: 0.0.0.0</msg>
<msg timestamp="20201221 22:21:48.364" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102f85e50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20201221 22:21:48.365" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102fa71c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20201221 22:21:48.365" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102fa7310&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20201221 22:21:48.370" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20201221 22:21:48.366" endtime="20201221 22:21:48.370"></status>
</kw>
<msg timestamp="20201221 22:21:48.371" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20201221 22:21:48.379" level="FAIL">MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102fa7490&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20201221 22:21:48.356" endtime="20201221 22:21:48.379"></status>
</kw>
<status status="FAIL" starttime="20201221 22:21:48.356" endtime="20201221 22:21:48.379"></status>
</kw>
<kw name="Close Application" library="AppiumLibrary" type="teardown">
<doc>Closes the current application and also close webdriver session.</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20201221 22:21:48.380" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20201221 22:21:48.380" endtime="20201221 22:21:48.380"></status>
</kw>
<msg timestamp="20201221 22:21:48.382" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20201221 22:21:48.382" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20201221 22:21:48.379" endtime="20201221 22:21:48.382">No application is open</status>
</kw>
<doc>Add Steps And Verify If Added correctly in Home and Weekly Progress</doc>
<status status="FAIL" starttime="20201221 22:21:48.355" endtime="20201221 22:21:48.382" critical="yes">Setup failed:
MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102fa7490&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

Also teardown failed:
No application is open</status>
</test>
<status status="FAIL" starttime="20201221 22:21:48.040" endtime="20201221 22:21:48.383"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="TestCases">TestCases</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20201221 22:21:48.364" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102f85e50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20201221 22:21:48.365" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102fa71c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20201221 22:21:48.365" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x102fa7310&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /wd/hub/session</msg>
<msg timestamp="20201221 22:21:48.371" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20201221 22:21:48.382" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
